// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class Currency {
  private Currency() { }
  public static final byte UNKNOWN = 0;
  public static final byte BAT = 1;
  public static final byte BCH = 2;
  public static final byte BTC = 3;
  public static final byte CVC = 4;
  public static final byte DAI = 5;
  public static final byte DNT = 6;
  public static final byte EOS = 7;
  public static final byte ETC = 8;
  public static final byte ETH = 9;
  public static final byte EUR = 10;
  public static final byte GBP = 11;
  public static final byte GNT = 12;
  public static final byte LINK = 13;
  public static final byte LOOM = 14;
  public static final byte LTC = 15;
  public static final byte MANA = 16;
  public static final byte REP = 17;
  public static final byte USD = 18;
  public static final byte USDC = 19;
  public static final byte XLM = 20;
  public static final byte XRP = 21;
  public static final byte ZEC = 22;
  public static final byte ZRX = 23;
  public static final byte XTZ = 24;
  public static final byte ALGO = 25;
  public static final byte DASH = 26;
  public static final byte OXT = 27;
  public static final byte ATOM = 28;
  public static final byte KNC = 29;

  public static final String[] names = { "UNKNOWN", "BAT", "BCH", "BTC", "CVC", "DAI", "DNT", "EOS", "ETC", "ETH", "EUR", "GBP", "GNT", "LINK", "LOOM", "LTC", "MANA", "REP", "USD", "USDC", "XLM", "XRP", "ZEC", "ZRX", "XTZ", "ALGO", "DASH", "OXT", "ATOM", "KNC", };

  public static String name(int e) { return names[e]; }
}

