// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class Currency {
  private Currency() { }
  public static final byte UNKNOWN = 0;
  public static final byte BAT = 1;
  public static final byte BCH = 2;
  public static final byte BTC = 3;
  public static final byte CVC = 4;
  public static final byte DAI = 5;
  public static final byte DNT = 6;
  public static final byte EOS = 7;
  public static final byte ETC = 8;
  public static final byte ETH = 9;
  public static final byte EUR = 10;
  public static final byte GBP = 11;
  public static final byte GNT = 12;
  public static final byte LINK = 13;
  public static final byte LOOM = 14;
  public static final byte LTC = 15;
  public static final byte MANA = 16;
  public static final byte REP = 17;
  public static final byte USD = 18;
  public static final byte USDC = 19;
  public static final byte XLM = 20;
  public static final byte XRP = 21;
  public static final byte ZEC = 22;
  public static final byte ZRX = 23;
  public static final byte XTZ = 24;
  public static final byte ALGO = 25;
  public static final byte DASH = 26;
  public static final byte OXT = 27;
  public static final byte ATOM = 28;
  public static final byte KNC = 29;
  public static final byte OMG = 30;
  public static final byte MKR = 31;
  public static final byte WBTC = 32;
  public static final byte NU = 33;
  public static final byte YFI = 34;
  public static final byte BAND = 35;
  public static final byte UMA = 36;
  public static final byte NMR = 37;
  public static final byte FIL = 38;
  public static final byte CGLD = 39;
  public static final byte LRC = 40;
  public static final byte COMP = 41;
  public static final byte UNI = 42;
  public static final byte REN = 43;
  public static final byte BAL = 44;

  public static final String[] names = { "UNKNOWN", "BAT", "BCH", "BTC", "CVC", "DAI", "DNT", "EOS", "ETC", "ETH", "EUR", "GBP", "GNT", "LINK", "LOOM", "LTC", "MANA", "REP", "USD", "USDC", "XLM", "XRP", "ZEC", "ZRX", "XTZ", "ALGO", "DASH", "OXT", "ATOM", "KNC", "OMG", "MKR", "WBTC", "NU", "YFI", "BAND", "UMA", "NMR", "FIL", "CGLD", "LRC", "COMP", "UNI", "REN", "BAL", };

  public static String name(int e) { return names[e]; }
}

