// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class Exchange {
  private Exchange() { }
  public static final byte COINBASE = 0;

  public static final String[] names = { "COINBASE", };

  public static String name(int e) { return names[e]; }
}

