// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class IncrementalPriceLevel extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public IncrementalPriceLevel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long price() { return bb.getLong(bb_pos + 0); }
  public long quantity() { return bb.getLong(bb_pos + 8); }
  public long side() { return bb.getLong(bb_pos + 16); }

  public static int createIncrementalPriceLevel(FlatBufferBuilder builder, long price, long quantity, long side) {
    builder.prep(8, 24);
    builder.putLong(side);
    builder.putLong(quantity);
    builder.putLong(price);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public IncrementalPriceLevel get(int j) { return get(new IncrementalPriceLevel(), j); }
    public IncrementalPriceLevel get(IncrementalPriceLevel obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

