// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class InstrumentType {
  private InstrumentType() { }
  public static final byte UNKNOWN = 0;
  public static final byte STOCK = 1;
  public static final byte FUTURE = 2;
  public static final byte OPTION = 3;
  public static final byte FOREX = 4;
  public static final byte CRYPTO = 5;

  public static final String[] names = { "UNKNOWN", "STOCK", "FUTURE", "OPTION", "FOREX", "CRYPTO", };

  public static String name(int e) { return names[e]; }
}

