// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class InstrumentRefreshRequest extends Table {
  public static InstrumentRefreshRequest getRootAsInstrumentRefreshRequest(ByteBuffer _bb) { return getRootAsInstrumentRefreshRequest(_bb, new InstrumentRefreshRequest()); }
  public static InstrumentRefreshRequest getRootAsInstrumentRefreshRequest(ByteBuffer _bb, InstrumentRefreshRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public InstrumentRefreshRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startInstrumentRefreshRequest(FlatBufferBuilder builder) { builder.startObject(0); }
  public static int endInstrumentRefreshRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

