// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class OrderRequest extends Table {
  public static OrderRequest getRootAsOrderRequest(ByteBuffer _bb) { return getRootAsOrderRequest(_bb, new OrderRequest()); }
  public static OrderRequest getRootAsOrderRequest(ByteBuffer _bb, OrderRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public OrderRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long timestamp() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long securityId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long price() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long quantity() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public byte side() { int o = __offset(12); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String orderId() { int o = __offset(14); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer orderIdAsByteBuffer() { return __vector_as_bytebuffer(14, 1); }
  public ByteBuffer orderIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 14, 1); }
  public byte tif() { int o = __offset(16); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createOrderRequest(FlatBufferBuilder builder,
      long timestamp,
      long security_id,
      long price,
      long quantity,
      byte side,
      int order_idOffset,
      byte tif) {
    builder.startObject(7);
    OrderRequest.addQuantity(builder, quantity);
    OrderRequest.addPrice(builder, price);
    OrderRequest.addSecurityId(builder, security_id);
    OrderRequest.addTimestamp(builder, timestamp);
    OrderRequest.addOrderId(builder, order_idOffset);
    OrderRequest.addTif(builder, tif);
    OrderRequest.addSide(builder, side);
    return OrderRequest.endOrderRequest(builder);
  }

  public static void startOrderRequest(FlatBufferBuilder builder) { builder.startObject(7); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(0, timestamp, 0L); }
  public static void addSecurityId(FlatBufferBuilder builder, long securityId) { builder.addLong(1, securityId, 0L); }
  public static void addPrice(FlatBufferBuilder builder, long price) { builder.addLong(2, price, 0L); }
  public static void addQuantity(FlatBufferBuilder builder, long quantity) { builder.addLong(3, quantity, 0L); }
  public static void addSide(FlatBufferBuilder builder, byte side) { builder.addByte(4, side, 0); }
  public static void addOrderId(FlatBufferBuilder builder, int orderIdOffset) { builder.addOffset(5, orderIdOffset, 0); }
  public static void addTif(FlatBufferBuilder builder, byte tif) { builder.addByte(6, tif, 0); }
  public static int endOrderRequest(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

