// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class OrderSide {
  private OrderSide() { }
  public static final byte UNKNOWN = 0;
  public static final byte BID = 1;
  public static final byte ASK = 2;

  public static final String[] names = { "UNKNOWN", "BID", "ASK", };

  public static String name(int e) { return names[e]; }
}

