// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class OrderStatus {
  private OrderStatus() { }
  public static final byte UNKNOWN = 0;
  public static final byte IN_FLIGHT = 1;
  public static final byte CANCEL_IN_FLIGHT = 2;
  public static final byte REPLACE_IN_FLIGHT = 3;
  public static final byte NEW = 4;
  public static final byte ACCEPTED = 5;
  public static final byte CANCELLED = 6;
  public static final byte REPLACED = 7;
  public static final byte REJECTED = 8;
  public static final byte CANCEL_REJECTED = 9;
  public static final byte REPLACE_REJECTED = 10;
  public static final byte FILLED = 11;
  public static final byte PARTIALLY_FILLED = 12;
  public static final byte EXPIRED = 13;
  public static final byte DONE = 14;

  public static final String[] names = { "UNKNOWN", "IN_FLIGHT", "CANCEL_IN_FLIGHT", "REPLACE_IN_FLIGHT", "NEW", "ACCEPTED", "CANCELLED", "REPLACED", "REJECTED", "CANCEL_REJECTED", "REPLACE_REJECTED", "FILLED", "PARTIALLY_FILLED", "EXPIRED", "DONE", };

  public static String name(int e) { return names[e]; }
}

