// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class RequestType {
  private RequestType() { }
  public static final byte INVALID = 0;
  public static final byte ALL = 1;
  public static final byte ID = 2;
  public static final byte EXCHANGE = 3;
  public static final byte PRODUCT = 4;

  public static final String[] names = { "INVALID", "ALL", "ID", "EXCHANGE", "PRODUCT", };

  public static String name(int e) { return names[e]; }
}

