// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class RiskRequestType {
  private RiskRequestType() { }
  public static final byte ALL = 0;
  public static final byte TRADER = 1;
  public static final byte SECURITY_ID = 2;
  public static final byte BOOK = 3;

  public static final String[] names = { "ALL", "TRADER", "SECURITY_ID", "BOOK", };

  public static String name(int e) { return names[e]; }
}

