// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SequenceNumber extends Table {
  public static SequenceNumber getRootAsSequenceNumber(ByteBuffer _bb) { return getRootAsSequenceNumber(_bb, new SequenceNumber()); }
  public static SequenceNumber getRootAsSequenceNumber(ByteBuffer _bb, SequenceNumber obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public SequenceNumber __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long value() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createSequenceNumber(FlatBufferBuilder builder,
      long value) {
    builder.startObject(1);
    SequenceNumber.addValue(builder, value);
    return SequenceNumber.endSequenceNumber(builder);
  }

  public static void startSequenceNumber(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addLong(0, value, 0L); }
  public static int endSequenceNumber(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

