// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class Side {
  private Side() { }
  public static final byte UNKNOWN = 0;
  public static final byte BUY = 1;
  public static final byte SELL = 2;

  public static final String[] names = { "UNKNOWN", "BUY", "SELL", };

  public static String name(int e) { return names[e]; }
}

