// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SnapshotPriceLevel extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SnapshotPriceLevel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long price() { return bb.getLong(bb_pos + 0); }
  public long quantity() { return bb.getLong(bb_pos + 8); }

  public static int createSnapshotPriceLevel(FlatBufferBuilder builder, long price, long quantity) {
    builder.prep(8, 16);
    builder.putLong(quantity);
    builder.putLong(price);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SnapshotPriceLevel get(int j) { return get(new SnapshotPriceLevel(), j); }
    public SnapshotPriceLevel get(SnapshotPriceLevel obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

