// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Snapshot extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Snapshot getRootAsSnapshot(ByteBuffer _bb) { return getRootAsSnapshot(_bb, new Snapshot()); }
  public static Snapshot getRootAsSnapshot(ByteBuffer _bb, Snapshot obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Snapshot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long timestamp() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public long securityId() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public krypto.serialization.SnapshotPriceLevel bids(int j) { return bids(new krypto.serialization.SnapshotPriceLevel(), j); }
  public krypto.serialization.SnapshotPriceLevel bids(krypto.serialization.SnapshotPriceLevel obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int bidsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public krypto.serialization.SnapshotPriceLevel.Vector bidsVector() { return bidsVector(new krypto.serialization.SnapshotPriceLevel.Vector()); }
  public krypto.serialization.SnapshotPriceLevel.Vector bidsVector(krypto.serialization.SnapshotPriceLevel.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }
  public krypto.serialization.SnapshotPriceLevel asks(int j) { return asks(new krypto.serialization.SnapshotPriceLevel(), j); }
  public krypto.serialization.SnapshotPriceLevel asks(krypto.serialization.SnapshotPriceLevel obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o) + j * 16, bb) : null; }
  public int asksLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public krypto.serialization.SnapshotPriceLevel.Vector asksVector() { return asksVector(new krypto.serialization.SnapshotPriceLevel.Vector()); }
  public krypto.serialization.SnapshotPriceLevel.Vector asksVector(krypto.serialization.SnapshotPriceLevel.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 16, bb) : null; }

  public static int createSnapshot(FlatBufferBuilder builder,
      long timestamp,
      long security_id,
      int bidsOffset,
      int asksOffset) {
    builder.startTable(4);
    Snapshot.addSecurityId(builder, security_id);
    Snapshot.addTimestamp(builder, timestamp);
    Snapshot.addAsks(builder, asksOffset);
    Snapshot.addBids(builder, bidsOffset);
    return Snapshot.endSnapshot(builder);
  }

  public static void startSnapshot(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addTimestamp(FlatBufferBuilder builder, long timestamp) { builder.addLong(0, timestamp, 0L); }
  public static void addSecurityId(FlatBufferBuilder builder, long securityId) { builder.addLong(1, securityId, 0L); }
  public static void addBids(FlatBufferBuilder builder, int bidsOffset) { builder.addOffset(2, bidsOffset, 0); }
  public static void startBidsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static void addAsks(FlatBufferBuilder builder, int asksOffset) { builder.addOffset(3, asksOffset, 0); }
  public static void startAsksVector(FlatBufferBuilder builder, int numElems) { builder.startVector(16, numElems, 8); }
  public static int endSnapshot(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Snapshot get(int j) { return get(new Snapshot(), j); }
    public Snapshot get(Snapshot obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

