// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

public final class TimeInForce {
  private TimeInForce() { }
  public static final byte DAY = 0;
  public static final byte IOC = 1;
  public static final byte FOK = 2;
  public static final byte GTC = 3;
  public static final byte GTT = 4;

  public static final String[] names = { "DAY", "IOC", "FOK", "GTC", "GTT", };

  public static String name(int e) { return names[e]; }
}

