// automatically generated by the FlatBuffers compiler, do not modify

package krypto.serialization;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TraderPosition extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static TraderPosition getRootAsTraderPosition(ByteBuffer _bb) { return getRootAsTraderPosition(_bb, new TraderPosition()); }
  public static TraderPosition getRootAsTraderPosition(ByteBuffer _bb, TraderPosition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TraderPosition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String trader() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer traderAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer traderInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public krypto.serialization.Position positions(int j) { return positions(new krypto.serialization.Position(), j); }
  public krypto.serialization.Position positions(krypto.serialization.Position obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o) + j * 40, bb) : null; }
  public int positionsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public krypto.serialization.Position.Vector positionsVector() { return positionsVector(new krypto.serialization.Position.Vector()); }
  public krypto.serialization.Position.Vector positionsVector(krypto.serialization.Position.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 40, bb) : null; }

  public static int createTraderPosition(FlatBufferBuilder builder,
      int traderOffset,
      int positionsOffset) {
    builder.startTable(2);
    TraderPosition.addPositions(builder, positionsOffset);
    TraderPosition.addTrader(builder, traderOffset);
    return TraderPosition.endTraderPosition(builder);
  }

  public static void startTraderPosition(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addTrader(FlatBufferBuilder builder, int traderOffset) { builder.addOffset(0, traderOffset, 0); }
  public static void addPositions(FlatBufferBuilder builder, int positionsOffset) { builder.addOffset(1, positionsOffset, 0); }
  public static void startPositionsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(40, numElems, 8); }
  public static int endTraderPosition(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TraderPosition get(int j) { return get(new TraderPosition(), j); }
    public TraderPosition get(TraderPosition obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

