// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var krypto = krypto || {};

/**
 * @const
 * @namespace
 */
krypto.serialization = krypto.serialization || {};

/**
 * @enum
 */
krypto.serialization.Side = {
  UNKNOWN: 0,
  BUY: 1,
  SELL: 2
};

/**
 * @enum
 */
krypto.serialization.OrderSide = {
  UNKNOWN: 0,
  BID: 1,
  ASK: 2
};

/**
 * @enum
 */
krypto.serialization.OrderStatus = {
  IN_FLIGHT: 0,
  NEW: 1,
  ACCEPTED: 2,
  CANCELLED: 3,
  REJECTED: 4,
  FILLED: 5,
  PARTIALLY_FILLED: 6
};

/**
 * @enum
 */
krypto.serialization.InstrumentType = {
  UNKNOWN: 0,
  STOCK: 1,
  FUTURE: 2,
  OPTION: 3,
  FOREX: 4,
  CRYPTO: 5
};

/**
 * @enum
 */
krypto.serialization.Currency = {
  UNKNOWN: 0,
  BAT: 1,
  BCH: 2,
  BTC: 3,
  CVC: 4,
  DAI: 5,
  DNT: 6,
  EOS: 7,
  ETC: 8,
  ETH: 9,
  EUR: 10,
  GBP: 11,
  GNT: 12,
  LINK: 13,
  LOOM: 14,
  LTC: 15,
  MANA: 16,
  REP: 17,
  USD: 18,
  USDC: 19,
  XLM: 20,
  XRP: 21,
  ZEC: 22,
  ZRX: 23,
  XTZ: 24
};

/**
 * @enum
 */
krypto.serialization.RequestType = {
  INVALID: 0,
  ALL: 1,
  ID: 2,
  EXCHANGE: 3,
  PRODUCT: 4
};

/**
 * @constructor
 */
krypto.serialization.SequenceNumber = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.SequenceNumber}
 */
krypto.serialization.SequenceNumber.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.SequenceNumber=} obj
 * @returns {krypto.serialization.SequenceNumber}
 */
krypto.serialization.SequenceNumber.getRootAsSequenceNumber = function (bb, obj) {
  return (obj || new krypto.serialization.SequenceNumber).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.SequenceNumber.prototype.value = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.SequenceNumber.startSequenceNumber = function (builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} value
 */
krypto.serialization.SequenceNumber.addValue = function (builder, value) {
  builder.addFieldInt64(0, value, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.SequenceNumber.endSequenceNumber = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.Instrument = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.Instrument}
 */
krypto.serialization.Instrument.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.Instrument=} obj
 * @returns {krypto.serialization.Instrument}
 */
krypto.serialization.Instrument.getRootAsInstrument = function (bb, obj) {
  return (obj || new krypto.serialization.Instrument).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Instrument.prototype.id = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {krypto.serialization.InstrumentType}
 */
krypto.serialization.Instrument.prototype.type = function () {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {krypto.serialization.InstrumentType} */ (this.bb.readInt8(this.bb_pos + offset)) : krypto.serialization.InstrumentType.UNKNOWN;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
krypto.serialization.Instrument.prototype.symbol = function (optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
krypto.serialization.Instrument.prototype.exchange = function (optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
krypto.serialization.Instrument.prototype.exchangeSymbol = function (optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
krypto.serialization.Instrument.prototype.tickSize = function () {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
krypto.serialization.Instrument.prototype.minSize = function () {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
krypto.serialization.Instrument.prototype.maxSize = function () {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {krypto.serialization.Currency}
 */
krypto.serialization.Instrument.prototype.cryptoBase = function () {
  var offset = this.bb.__offset(this.bb_pos, 20);
  return offset ? /** @type {krypto.serialization.Currency} */ (this.bb.readInt8(this.bb_pos + offset)) : krypto.serialization.Currency.UNKNOWN;
};

/**
 * @returns {krypto.serialization.Currency}
 */
krypto.serialization.Instrument.prototype.cryptoQuote = function () {
  var offset = this.bb.__offset(this.bb_pos, 22);
  return offset ? /** @type {krypto.serialization.Currency} */ (this.bb.readInt8(this.bb_pos + offset)) : krypto.serialization.Currency.UNKNOWN;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.Instrument.startInstrument = function (builder) {
  builder.startObject(10);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} id
 */
krypto.serialization.Instrument.addId = function (builder, id) {
  builder.addFieldInt64(0, id, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {krypto.serialization.InstrumentType} type
 */
krypto.serialization.Instrument.addType = function (builder, type) {
  builder.addFieldInt8(1, type, krypto.serialization.InstrumentType.UNKNOWN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} symbolOffset
 */
krypto.serialization.Instrument.addSymbol = function (builder, symbolOffset) {
  builder.addFieldOffset(2, symbolOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} exchangeOffset
 */
krypto.serialization.Instrument.addExchange = function (builder, exchangeOffset) {
  builder.addFieldOffset(3, exchangeOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} exchangeSymbolOffset
 */
krypto.serialization.Instrument.addExchangeSymbol = function (builder, exchangeSymbolOffset) {
  builder.addFieldOffset(4, exchangeSymbolOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} tickSize
 */
krypto.serialization.Instrument.addTickSize = function (builder, tickSize) {
  builder.addFieldFloat64(5, tickSize, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} minSize
 */
krypto.serialization.Instrument.addMinSize = function (builder, minSize) {
  builder.addFieldFloat64(6, minSize, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} maxSize
 */
krypto.serialization.Instrument.addMaxSize = function (builder, maxSize) {
  builder.addFieldFloat64(7, maxSize, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {krypto.serialization.Currency} cryptoBase
 */
krypto.serialization.Instrument.addCryptoBase = function (builder, cryptoBase) {
  builder.addFieldInt8(8, cryptoBase, krypto.serialization.Currency.UNKNOWN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {krypto.serialization.Currency} cryptoQuote
 */
krypto.serialization.Instrument.addCryptoQuote = function (builder, cryptoQuote) {
  builder.addFieldInt8(9, cryptoQuote, krypto.serialization.Currency.UNKNOWN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.Instrument.endInstrument = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.Quote = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.Quote}
 */
krypto.serialization.Quote.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.Quote=} obj
 * @returns {krypto.serialization.Quote}
 */
krypto.serialization.Quote.getRootAsQuote = function (bb, obj) {
  return (obj || new krypto.serialization.Quote).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Quote.prototype.timestamp = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Quote.prototype.securityId = function () {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Quote.prototype.bid = function () {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Quote.prototype.ask = function () {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Quote.prototype.last = function () {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Quote.prototype.bidQuantity = function () {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Quote.prototype.askQuantity = function () {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Quote.prototype.lastQuantity = function () {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.Quote.startQuote = function (builder) {
  builder.startObject(8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
krypto.serialization.Quote.addTimestamp = function (builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} securityId
 */
krypto.serialization.Quote.addSecurityId = function (builder, securityId) {
  builder.addFieldInt64(1, securityId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} bid
 */
krypto.serialization.Quote.addBid = function (builder, bid) {
  builder.addFieldInt64(2, bid, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} ask
 */
krypto.serialization.Quote.addAsk = function (builder, ask) {
  builder.addFieldInt64(3, ask, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} last
 */
krypto.serialization.Quote.addLast = function (builder, last) {
  builder.addFieldInt64(4, last, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} bidQuantity
 */
krypto.serialization.Quote.addBidQuantity = function (builder, bidQuantity) {
  builder.addFieldInt64(5, bidQuantity, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} askQuantity
 */
krypto.serialization.Quote.addAskQuantity = function (builder, askQuantity) {
  builder.addFieldInt64(6, askQuantity, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} lastQuantity
 */
krypto.serialization.Quote.addLastQuantity = function (builder, lastQuantity) {
  builder.addFieldInt64(7, lastQuantity, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.Quote.endQuote = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.SnapshotPriceLevel = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.SnapshotPriceLevel}
 */
krypto.serialization.SnapshotPriceLevel.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.SnapshotPriceLevel.prototype.price = function () {
  return this.bb.readInt64(this.bb_pos);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.SnapshotPriceLevel.prototype.quantity = function () {
  return this.bb.readInt64(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} price
 * @param {flatbuffers.Long} quantity
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.SnapshotPriceLevel.createSnapshotPriceLevel = function (builder, price, quantity) {
  builder.prep(8, 16);
  builder.writeInt64(quantity);
  builder.writeInt64(price);
  return builder.offset();
};

/**
 * @constructor
 */
krypto.serialization.Snapshot = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.Snapshot}
 */
krypto.serialization.Snapshot.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.Snapshot=} obj
 * @returns {krypto.serialization.Snapshot}
 */
krypto.serialization.Snapshot.getRootAsSnapshot = function (bb, obj) {
  return (obj || new krypto.serialization.Snapshot).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Snapshot.prototype.timestamp = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Snapshot.prototype.securityId = function () {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {number} index
 * @param {krypto.serialization.SnapshotPriceLevel=} obj
 * @returns {krypto.serialization.SnapshotPriceLevel}
 */
krypto.serialization.Snapshot.prototype.bids = function (index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new krypto.serialization.SnapshotPriceLevel).__init(this.bb.__vector(this.bb_pos + offset) + index * 16, this.bb) : null;
};

/**
 * @returns {number}
 */
krypto.serialization.Snapshot.prototype.bidsLength = function () {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {number} index
 * @param {krypto.serialization.SnapshotPriceLevel=} obj
 * @returns {krypto.serialization.SnapshotPriceLevel}
 */
krypto.serialization.Snapshot.prototype.asks = function (index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new krypto.serialization.SnapshotPriceLevel).__init(this.bb.__vector(this.bb_pos + offset) + index * 16, this.bb) : null;
};

/**
 * @returns {number}
 */
krypto.serialization.Snapshot.prototype.asksLength = function () {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.Snapshot.startSnapshot = function (builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
krypto.serialization.Snapshot.addTimestamp = function (builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} securityId
 */
krypto.serialization.Snapshot.addSecurityId = function (builder, securityId) {
  builder.addFieldInt64(1, securityId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} bidsOffset
 */
krypto.serialization.Snapshot.addBids = function (builder, bidsOffset) {
  builder.addFieldOffset(2, bidsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
krypto.serialization.Snapshot.startBidsVector = function (builder, numElems) {
  builder.startVector(16, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} asksOffset
 */
krypto.serialization.Snapshot.addAsks = function (builder, asksOffset) {
  builder.addFieldOffset(3, asksOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
krypto.serialization.Snapshot.startAsksVector = function (builder, numElems) {
  builder.startVector(16, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.Snapshot.endSnapshot = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.IncrementalPriceLevel = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.IncrementalPriceLevel}
 */
krypto.serialization.IncrementalPriceLevel.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.IncrementalPriceLevel.prototype.price = function () {
  return this.bb.readInt64(this.bb_pos);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.IncrementalPriceLevel.prototype.quantity = function () {
  return this.bb.readInt64(this.bb_pos + 8);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.IncrementalPriceLevel.prototype.side = function () {
  return this.bb.readInt64(this.bb_pos + 16);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} price
 * @param {flatbuffers.Long} quantity
 * @param {flatbuffers.Long} side
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.IncrementalPriceLevel.createIncrementalPriceLevel = function (builder, price, quantity, side) {
  builder.prep(8, 24);
  builder.writeInt64(side);
  builder.writeInt64(quantity);
  builder.writeInt64(price);
  return builder.offset();
};

/**
 * @constructor
 */
krypto.serialization.Incremental = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.Incremental}
 */
krypto.serialization.Incremental.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.Incremental=} obj
 * @returns {krypto.serialization.Incremental}
 */
krypto.serialization.Incremental.getRootAsIncremental = function (bb, obj) {
  return (obj || new krypto.serialization.Incremental).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Incremental.prototype.timestamp = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Incremental.prototype.securityId = function () {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {number} index
 * @param {krypto.serialization.IncrementalPriceLevel=} obj
 * @returns {krypto.serialization.IncrementalPriceLevel}
 */
krypto.serialization.Incremental.prototype.updates = function (index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? (obj || new krypto.serialization.IncrementalPriceLevel).__init(this.bb.__vector(this.bb_pos + offset) + index * 24, this.bb) : null;
};

/**
 * @returns {number}
 */
krypto.serialization.Incremental.prototype.updatesLength = function () {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.Incremental.startIncremental = function (builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
krypto.serialization.Incremental.addTimestamp = function (builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} securityId
 */
krypto.serialization.Incremental.addSecurityId = function (builder, securityId) {
  builder.addFieldInt64(1, securityId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} updatesOffset
 */
krypto.serialization.Incremental.addUpdates = function (builder, updatesOffset) {
  builder.addFieldOffset(2, updatesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
krypto.serialization.Incremental.startUpdatesVector = function (builder, numElems) {
  builder.startVector(24, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.Incremental.endIncremental = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.Trade = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.Trade}
 */
krypto.serialization.Trade.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.Trade=} obj
 * @returns {krypto.serialization.Trade}
 */
krypto.serialization.Trade.getRootAsTrade = function (bb, obj) {
  return (obj || new krypto.serialization.Trade).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Trade.prototype.timestamp = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Trade.prototype.securityId = function () {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Trade.prototype.price = function () {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Trade.prototype.quantity = function () {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {krypto.serialization.Side}
 */
krypto.serialization.Trade.prototype.side = function () {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? /** @type {krypto.serialization.Side} */ (this.bb.readInt8(this.bb_pos + offset)) : krypto.serialization.Side.UNKNOWN;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
krypto.serialization.Trade.prototype.tradeId = function (optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.Trade.startTrade = function (builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
krypto.serialization.Trade.addTimestamp = function (builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} securityId
 */
krypto.serialization.Trade.addSecurityId = function (builder, securityId) {
  builder.addFieldInt64(1, securityId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} price
 */
krypto.serialization.Trade.addPrice = function (builder, price) {
  builder.addFieldInt64(2, price, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} quantity
 */
krypto.serialization.Trade.addQuantity = function (builder, quantity) {
  builder.addFieldInt64(3, quantity, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {krypto.serialization.Side} side
 */
krypto.serialization.Trade.addSide = function (builder, side) {
  builder.addFieldInt8(4, side, krypto.serialization.Side.UNKNOWN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} tradeIdOffset
 */
krypto.serialization.Trade.addTradeId = function (builder, tradeIdOffset) {
  builder.addFieldOffset(5, tradeIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.Trade.endTrade = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.InstrumentRequest = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.InstrumentRequest}
 */
krypto.serialization.InstrumentRequest.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.InstrumentRequest=} obj
 * @returns {krypto.serialization.InstrumentRequest}
 */
krypto.serialization.InstrumentRequest.getRootAsInstrumentRequest = function (bb, obj) {
  return (obj || new krypto.serialization.InstrumentRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {krypto.serialization.RequestType}
 */
krypto.serialization.InstrumentRequest.prototype.type = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {krypto.serialization.RequestType} */ (this.bb.readInt8(this.bb_pos + offset)) : krypto.serialization.RequestType.INVALID;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.InstrumentRequest.startInstrumentRequest = function (builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {krypto.serialization.RequestType} type
 */
krypto.serialization.InstrumentRequest.addType = function (builder, type) {
  builder.addFieldInt8(0, type, krypto.serialization.RequestType.INVALID);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.InstrumentRequest.endInstrumentRequest = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.InstrumentResponse = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.InstrumentResponse}
 */
krypto.serialization.InstrumentResponse.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.InstrumentResponse=} obj
 * @returns {krypto.serialization.InstrumentResponse}
 */
krypto.serialization.InstrumentResponse.getRootAsInstrumentResponse = function (bb, obj) {
  return (obj || new krypto.serialization.InstrumentResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {number} index
 * @param {krypto.serialization.Instrument=} obj
 * @returns {krypto.serialization.Instrument}
 */
krypto.serialization.InstrumentResponse.prototype.instruments = function (index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new krypto.serialization.Instrument).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
krypto.serialization.InstrumentResponse.prototype.instrumentsLength = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.InstrumentResponse.startInstrumentResponse = function (builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} instrumentsOffset
 */
krypto.serialization.InstrumentResponse.addInstruments = function (builder, instrumentsOffset) {
  builder.addFieldOffset(0, instrumentsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.InstrumentResponse.createInstrumentsVector = function (builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
krypto.serialization.InstrumentResponse.startInstrumentsVector = function (builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.InstrumentResponse.endInstrumentResponse = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.OrderRequest = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.OrderRequest}
 */
krypto.serialization.OrderRequest.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.OrderRequest=} obj
 * @returns {krypto.serialization.OrderRequest}
 */
krypto.serialization.OrderRequest.getRootAsOrderRequest = function (bb, obj) {
  return (obj || new krypto.serialization.OrderRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.OrderRequest.prototype.timestamp = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.OrderRequest.prototype.securityId = function () {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.OrderRequest.prototype.price = function () {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.OrderRequest.prototype.quantity = function () {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {krypto.serialization.Side}
 */
krypto.serialization.OrderRequest.prototype.side = function () {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? /** @type {krypto.serialization.Side} */ (this.bb.readInt8(this.bb_pos + offset)) : krypto.serialization.Side.UNKNOWN;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
krypto.serialization.OrderRequest.prototype.orderId = function (optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.OrderRequest.startOrderRequest = function (builder) {
  builder.startObject(6);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
krypto.serialization.OrderRequest.addTimestamp = function (builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} securityId
 */
krypto.serialization.OrderRequest.addSecurityId = function (builder, securityId) {
  builder.addFieldInt64(1, securityId, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} price
 */
krypto.serialization.OrderRequest.addPrice = function (builder, price) {
  builder.addFieldInt64(2, price, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} quantity
 */
krypto.serialization.OrderRequest.addQuantity = function (builder, quantity) {
  builder.addFieldInt64(3, quantity, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {krypto.serialization.Side} side
 */
krypto.serialization.OrderRequest.addSide = function (builder, side) {
  builder.addFieldInt8(4, side, krypto.serialization.Side.UNKNOWN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} orderIdOffset
 */
krypto.serialization.OrderRequest.addOrderId = function (builder, orderIdOffset) {
  builder.addFieldOffset(5, orderIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.OrderRequest.endOrderRequest = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.OrderUpdate = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.OrderUpdate}
 */
krypto.serialization.OrderUpdate.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.OrderUpdate=} obj
 * @returns {krypto.serialization.OrderUpdate}
 */
krypto.serialization.OrderUpdate.getRootAsOrderUpdate = function (bb, obj) {
  return (obj || new krypto.serialization.OrderUpdate).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.OrderUpdate.prototype.timestamp = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
krypto.serialization.OrderUpdate.prototype.orderId = function (optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {krypto.serialization.OrderStatus}
 */
krypto.serialization.OrderUpdate.prototype.status = function () {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {krypto.serialization.OrderStatus} */ (this.bb.readInt8(this.bb_pos + offset)) : krypto.serialization.OrderStatus.IN_FLIGHT;
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.OrderUpdate.prototype.filledQuantity = function () {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.OrderUpdate.startOrderUpdate = function (builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
krypto.serialization.OrderUpdate.addTimestamp = function (builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} orderIdOffset
 */
krypto.serialization.OrderUpdate.addOrderId = function (builder, orderIdOffset) {
  builder.addFieldOffset(1, orderIdOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {krypto.serialization.OrderStatus} status
 */
krypto.serialization.OrderUpdate.addStatus = function (builder, status) {
  builder.addFieldInt8(2, status, krypto.serialization.OrderStatus.IN_FLIGHT);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} filledQuantity
 */
krypto.serialization.OrderUpdate.addFilledQuantity = function (builder, filledQuantity) {
  builder.addFieldInt64(3, filledQuantity, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.OrderUpdate.endOrderUpdate = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.Order = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.Order}
 */
krypto.serialization.Order.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.Order=} obj
 * @returns {krypto.serialization.Order}
 */
krypto.serialization.Order.getRootAsOrder = function (bb, obj) {
  return (obj || new krypto.serialization.Order).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {krypto.serialization.OrderRequest=} obj
 * @returns {krypto.serialization.OrderRequest|null}
 */
krypto.serialization.Order.prototype.request = function (obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new krypto.serialization.OrderRequest).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {number} index
 * @param {krypto.serialization.OrderUpdate=} obj
 * @returns {krypto.serialization.OrderUpdate}
 */
krypto.serialization.Order.prototype.updates = function (index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new krypto.serialization.OrderUpdate).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
};

/**
 * @returns {number}
 */
krypto.serialization.Order.prototype.updatesLength = function () {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
krypto.serialization.Order.prototype.fees = function () {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.Order.startOrder = function (builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} requestOffset
 */
krypto.serialization.Order.addRequest = function (builder, requestOffset) {
  builder.addFieldOffset(0, requestOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} updatesOffset
 */
krypto.serialization.Order.addUpdates = function (builder, updatesOffset) {
  builder.addFieldOffset(1, updatesOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<flatbuffers.Offset>} data
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.Order.createUpdatesVector = function (builder, data) {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
krypto.serialization.Order.startUpdatesVector = function (builder, numElems) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} fees
 */
krypto.serialization.Order.addFees = function (builder, fees) {
  builder.addFieldFloat64(2, fees, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.Order.endOrder = function (builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
krypto.serialization.Position = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.Position}
 */
krypto.serialization.Position.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Position.prototype.securityId = function () {
  return this.bb.readInt64(this.bb_pos);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.Position.prototype.position = function () {
  return this.bb.readInt64(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} security_id
 * @param {flatbuffers.Long} position
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.Position.createPosition = function (builder, security_id, position) {
  builder.prep(8, 16);
  builder.writeInt64(position);
  builder.writeInt64(security_id);
  return builder.offset();
};

/**
 * @constructor
 */
krypto.serialization.RiskSummary = function () {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {krypto.serialization.RiskSummary}
 */
krypto.serialization.RiskSummary.prototype.__init = function (i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {krypto.serialization.RiskSummary=} obj
 * @returns {krypto.serialization.RiskSummary}
 */
krypto.serialization.RiskSummary.getRootAsRiskSummary = function (bb, obj) {
  return (obj || new krypto.serialization.RiskSummary).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
krypto.serialization.RiskSummary.prototype.timestamp = function () {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @param {number} index
 * @param {krypto.serialization.Position=} obj
 * @returns {krypto.serialization.Position}
 */
krypto.serialization.RiskSummary.prototype.positions = function (index, obj) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? (obj || new krypto.serialization.Position).__init(this.bb.__vector(this.bb_pos + offset) + index * 16, this.bb) : null;
};

/**
 * @returns {number}
 */
krypto.serialization.RiskSummary.prototype.positionsLength = function () {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
krypto.serialization.RiskSummary.prototype.pnl = function () {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
krypto.serialization.RiskSummary.startRiskSummary = function (builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
krypto.serialization.RiskSummary.addTimestamp = function (builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} positionsOffset
 */
krypto.serialization.RiskSummary.addPositions = function (builder, positionsOffset) {
  builder.addFieldOffset(1, positionsOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
krypto.serialization.RiskSummary.startPositionsVector = function (builder, numElems) {
  builder.startVector(16, numElems, 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} pnl
 */
krypto.serialization.RiskSummary.addPnl = function (builder, pnl) {
  builder.addFieldFloat64(2, pnl, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
krypto.serialization.RiskSummary.endRiskSummary = function (builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
// this.krypto = krypto;

export default krypto;
